# Generated by Django 2.2.6 on 2019-12-09 20:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='author',
            field=models.CharField(default=datetime.datetime(2019, 12, 9, 20, 53, 16, 540077, tzinfo=utc), max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comments',
            name='published_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date published'),
        ),
    ]
