# Generated by Django 2.2.6 on 2019-12-10 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_auto_20191210_0342'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='question_title',
            field=models.TextField(default='New Quest'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='published_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date published'),
        ),
    ]
