# Generated by Django 2.2.6 on 2019-12-10 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_auto_20191210_0558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='published_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
