# Generated by Django 2.2.6 on 2019-12-10 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_auto_20191210_0604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='published_date',
            field=models.DateTimeField(verbose_name='published date'),
        ),
    ]
