# Generated by Django 2.2.6 on 2019-12-10 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0007_auto_20191210_0614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='question_title',
            field=models.TextField(),
        ),
    ]
