# Generated by Django 2.2.6 on 2019-12-10 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0009_auto_20191210_0639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='question_title',
            field=models.TextField(max_length=30),
        ),
    ]
